"""Module 5 - the orchestrator (plain Python, no LLM calls of its own).

Runs the full loop for one case or many, and aggregates results into a JSON
report:  transcript -> note -> audit -> judge ensemble -> summary.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .auditor import Finding, audit, flagged, to_dicts as findings_to_dicts
from .judge_ensemble import judge_findings, to_dicts as judged_to_dicts
from .note_generator import generate_note
from .scorer import score_case

_RESULTS_DIR = Path(__file__).resolve().parent.parent / "results"


@dataclass
class CaseResult:
    source: str                              # "synthetic" | "abridge" | "custom"
    label: str                               # human-readable case label
    transcript: str
    note: str
    note_provided: bool                      # True if note came in (not generated by us)
    findings: list[dict] = field(default_factory=list)        # all audited claims
    judged: list[dict] = field(default_factory=list)          # ensemble output for flagged
    ground_truth_traps: list[dict] = field(default_factory=list)  # synthetic only
    summary: dict[str, Any] = field(default_factory=dict)
    evaluation: dict[str, Any] = field(default_factory=dict)  # detection score vs traps (synthetic only)

    def to_dict(self) -> dict[str, Any]:
        return {
            "source": self.source,
            "label": self.label,
            "transcript": self.transcript,
            "note": self.note,
            "note_provided": self.note_provided,
            "findings": self.findings,
            "judged": self.judged,
            "ground_truth_traps": self.ground_truth_traps,
            "summary": self.summary,
            "evaluation": self.evaluation,
        }


def _summarize(all_findings: list[Finding], judged: list) -> dict[str, Any]:
    by_status: dict[str, int] = {}
    for f in all_findings:
        by_status[f.status] = by_status.get(f.status, 0) + 1
    confirmed = sum(1 for j in judged if j.consensus_verdict == "confirm")
    disagreements = sum(1 for j in judged if j.disagreement)
    high_confirmed = sum(
        1 for j in judged
        if j.consensus_verdict == "confirm" and j.severity_verdict == "high"
    )
    return {
        "claims_audited": len(all_findings),
        "flagged": sum(1 for f in all_findings if f.status != "supported"),
        "by_status": by_status,
        "escalated_to_judges": len(judged),
        "confirmed_discrepancies": confirmed,
        "high_severity_confirmed": high_confirmed,
        "judge_disagreements": disagreements,
    }


def run_case(
    transcript: str,
    note: str | None = None,
    source: str = "custom",
    label: str = "custom case",
    ground_truth_traps: list[dict] | None = None,
    fhir_context: dict[str, Any] | None = None,
    max_findings: int | None = 6,
) -> CaseResult:
    """Run one case through the full pipeline.

    If `note` is None we generate one with the note_generator (system under test);
    otherwise we audit the note that was handed in (e.g. Abridge's own note).
    `fhir_context` is the structured chart data - the auditor's second source of
    ground truth. `max_findings` caps how many flags escalate to the 3 judges.
    """
    note_provided = note is not None
    if note is None:
        note = generate_note(transcript)

    all_findings = audit(transcript, note, fhir_context=fhir_context)
    problems = flagged(all_findings)
    judged = judge_findings(
        transcript, note, problems, max_findings=max_findings, fhir_context=fhir_context
    )

    findings_dicts = findings_to_dicts(all_findings)
    judged_dicts = judged_to_dicts(judged)

    # Self-scoring: only synthetic cases carry ground-truth traps to grade against.
    evaluation = score_case(ground_truth_traps or [], findings_dicts, judged_dicts, note=note)

    return CaseResult(
        source=source,
        label=label,
        transcript=transcript,
        note=note,
        note_provided=note_provided,
        findings=findings_dicts,
        judged=judged_dicts,
        ground_truth_traps=ground_truth_traps or [],
        summary=_summarize(all_findings, judged),
        evaluation=evaluation,
    )


def run_synthetic(n: int = 3, max_findings: int | None = 6) -> list[CaseResult]:
    """Generate n synthetic trap cases and run each through the pipeline."""
    from dataclasses import asdict

    from .transcript_generator import generate_cases

    results = []
    for i, case in enumerate(generate_cases(n)):
        results.append(
            run_case(
                transcript=case.transcript,
                note=None,  # generate the note - this is the system under test
                source="synthetic",
                label=case.scenario or f"synthetic case {i + 1}",
                ground_truth_traps=[asdict(t) for t in case.traps],
                max_findings=max_findings,
            )
        )
    return results


def run_abridge(
    indices: list[int],
    regenerate_note: bool = False,
    max_findings: int | None = 6,
) -> list[CaseResult]:
    """Run selected Abridge encounters.

    regenerate_note=False audits Abridge's own clinician note (drift already in
    the wild); True regenerates a note with our scribe to stress-test it.
    """
    from .dataset import get_case

    results = []
    for idx in indices:
        c = get_case(idx)
        results.append(
            run_case(
                transcript=c.transcript,
                note=None if regenerate_note else c.note,
                source="abridge",
                label=f"[{idx}] {c.visit_title}",
                fhir_context=c.fhir_context,
                max_findings=max_findings,
            )
        )
    return results


def build_report(results: list[CaseResult], save: bool = True) -> dict[str, Any]:
    """Aggregate case results into one report dict, optionally written to results/."""
    totals = {
        "cases": len(results),
        "claims_audited": sum(r.summary.get("claims_audited", 0) for r in results),
        "flagged": sum(r.summary.get("flagged", 0) for r in results),
        "confirmed_discrepancies": sum(r.summary.get("confirmed_discrepancies", 0) for r in results),
        "high_severity_confirmed": sum(r.summary.get("high_severity_confirmed", 0) for r in results),
        "judge_disagreements": sum(r.summary.get("judge_disagreements", 0) for r in results),
    }

    # Detection score aggregated across the scored (synthetic) cases only.
    scored = [r.evaluation for r in results if r.evaluation]
    if scored:
        traps_total = sum(e.get("traps_total", 0) for e in scored)
        traps_drifted = sum(e.get("traps_drifted", 0) for e in scored)
        drift_caught = sum(e.get("drift_caught", 0) for e in scored)
        drift_confirmed = sum(e.get("drift_confirmed", 0) for e in scored)
        totals["evaluation"] = {
            "scored_cases": len(scored),
            "traps_total": traps_total,
            "traps_drifted": traps_drifted,
            "drift_caught": drift_caught,
            "drift_confirmed": drift_confirmed,
            "recall": round(drift_caught / traps_drifted, 3) if traps_drifted else None,
            "confirmed_recall": round(drift_confirmed / traps_drifted, 3) if traps_drifted else None,
        }
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "model": __import__("drift_harness.llm", fromlist=["MODEL"]).MODEL,
        "totals": totals,
        "cases": [r.to_dict() for r in results],
    }
    if save:
        _RESULTS_DIR.mkdir(exist_ok=True)
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        out = _RESULTS_DIR / f"report_{stamp}.json"
        out.write_text(json.dumps(report, indent=2), encoding="utf-8")
        report["_saved_to"] = str(out)
    return report


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Run the clinical-note drift harness.")
    parser.add_argument("--mode", choices=["synthetic", "abridge"], default="synthetic")
    parser.add_argument("--n", type=int, default=2, help="synthetic: number of cases")
    parser.add_argument("--indices", type=str, default="0,1", help="abridge: comma-separated indices")
    parser.add_argument("--regenerate-note", action="store_true", help="abridge: regenerate the note")
    args = parser.parse_args()

    if args.mode == "synthetic":
        results = run_synthetic(args.n)
    else:
        idxs = [int(x) for x in args.indices.split(",") if x.strip()]
        results = run_abridge(idxs, regenerate_note=args.regenerate_note)

    report = build_report(results, save=True)
    print(json.dumps(report["totals"], indent=2))
    print("saved to:", report.get("_saved_to"))
